spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  datasource:
#    url: jdbc:h2:file:./test-db;MODE=LEGACY;
    url: jdbc:h2:mem:planner
    driver-class-name: org.h2.Driver
    username: db_user
    password: db_pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8084